### ISSUE TITLE
Audio question

### ISSUE THREAD

**Issue by Forium777** [YaPlusDePQ/VoltaireTaMere#1]
There are audio questions between levels, so we can't let the program run by itself without check every questions.

Either add a speech-to-text feature or add an option to skip audio questions to let the program run by itself

Thanks!

**Comment by YaPlusDePQ** [comment]
the robot automatically deactivates the audio functions because of its lack of precision in this situation. This does not prevent you from being able to complete the level.

**Comment by Forium777** [comment]
It does, program is stucking when getting to a audio question! I've manually to validate the question, press next and get back to the soft and click on Auto again to make it start again

**Comment by YaPlusDePQ** [comment]
To be clear, VoltaireTaMere works as follows: - when an audio question is detected VoltaireTaMere will deactivate the audio functions of the Voltaire Project to have a Point-and-click function instead 
- If you reactivate the audio functions then the robot will not be able to answer the question because it does not support this function

Disabling audio functions does not prevent a level from being successful.

**Comment by YaPlusDePQ** [comment]
I just checked and no problem on my side. using version 3.6.4 on Chrome.
Try using Chrome if you don't or reinstall VTM.

**Comment by Forium777** [comment]
See by yourself
Any idea?

https://streamable.com/q2clmw

**Comment by YaPlusDePQ** [comment]
Okey so maybe the bot doesn’t deactive the audio automatically, but like i said before juste deactive audio by clicking on the button on the top right (with a speaker on it) and the bot while work perfectly.

**Comment by Forium777** [comment]
I can't see any audio clickable button. Can you provide a screenshot ?

**Comment by YaPlusDePQ** [comment]
![Uploading 754BED32-6293-4722-87AA-11A6084DDC0A.jpeg…]()

**Comment by YaPlusDePQ** [comment]
![B55CF9F9-4153-4931-ABB2-D948B25DD488](https://user-images.githubusercontent.com/74764309/118785782-7bb28d80-b891-11eb-85f6-e7fab81e96d3.jpeg)

**Comment by YaPlusDePQ** [comment]
Normally it is. And on the many account that i have ot is clickable. So the bot can’t do anything more for you
