### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by alexandergrin1** [YaPlusDePQ/VoltaireTaMere#4]
-rep trojan
![image](https://user-images.githubusercontent.com/94467823/142013596-37984c30-a8e4-411a-9abc-6913505a55b8.png)
Defender Windows
![image](https://user-images.githubusercontent.com/94467823/142014099-8aa6fc66-6459-4daf-81fb-bb7f8fc68b20.png)
VirusTotal

**Comment by YaPlusDePQ** [comment]
Bha j'ai pas d'autre truc a te répondre que si jamais t'as un doute lis le source code et exécute le script python de toi même pour voir que non ce n'est pas un Trojan. 
Il faut savoir qu'il est très difficile de détecter ce qui est un virus et ce qui n'en ai pas, la méthode la plus courante est de simplement bloquer les programme exécutables inconnu au catalogue des logiciels sur, comme VoltaireTaMere.

**Comment by VoXaN24** [comment]
Flag par McAfee aussi :c
