### ISSUE TITLE
désinstaller

### ISSUE THREAD

**Issue by matsuri69** [YaPlusDePQ/VoltaireTaMere#6]
voltaire ta mère se désinstalle tout seul et quand je le réinstalle et que je veux le lancer mon antivirus me dit que il ne peut pas lancer Voltairetamere car un trojan se trouve dedans. 
Regarde
<img width="356" alt="justificatif virus" src="https://user-images.githubusercontent.com/95659691/146193633-3f5e9f34-6e9a-4f0d-a3d0-648a7ce2e16c.PNG">

**Comment by YaPlusDePQ** [comment]
Deja c’est l’antivirus qui désinstalle VoltaireTaMere.

En suite il faut savoir qu’un antivirus n’as pas de moyen directe de comprendre un executable, c’est du code machine et donc on NE PEUX PAS recréer comme ça un code source a partir d’un executable. Donc un moyen safe mais pas precis que font les antivirus c’est: « si je connais pas le programme => c’est un virus je bloque ».
C’est pour ça d’ailleur que si tu as deja programmer et fais des langage compiler comme le C ton propre programme qui ne fais que « hello world » peut être bloquer.
Ensuite un moyen plus precis de détecter un logiciel malveillant et de regarder son comportement, VoltaireTaMere ecris dans des fichiers (commun mais peut être dangerieux), utilise le moteur de recherche (donc peut faure n’importe quoi theoriquement donc red flag) et enfin le pire, téléchargement d’autre logiciel ce qui est souvent un très gros res flag.
Les téléchargements de logiciel sont Chromedriver.exe qui doit être mis a jours régulièrement pour rester opérationnel avec Chrome et VoltaireTaMere en lui même lorsque il y a une mise a jours.
